### ISSUE TITLE
Submit to the ZAP Marketplace

### ISSUE THREAD

**Issue by psiinon** [gdgd009xcd/AutoMacroBuilderForZAP#2]
Just raise an issue via https://github.com/zaproxy/zaproxy/issues/new?assignees=&labels=marketplace&template=Third_party_addon.md

Once its on there we'd be very happy for you to write a guest post about this on the ZAP Blog: https://www.zaproxy.org/blog/
That should significantly increase its adoption :)

**Comment by gdgd009xcd** [comment]
Thank you for your suggestion.

but I already submitted issue(https://github.com/zaproxy/zaproxy/issues/6169)
currently, I 'm busy other work, so when it's time to tackle this, I will reopen it.
